apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  version: 8.0.15
  members: 3
  volumeClaimTemplate:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      storageClassName: hostpath
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
