---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  labels:
    app: mysql-router
spec:
  selector:
    app: mysql-router
  ports:
  - name: mysql-rw
    port: 6446
  - name: mysql-ro
    port: 6447
  - name: mysqlx-rw
    port: 64460
  - name: mysqlx-ro
    port: 64470
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  labels:
    app: mysql-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
      - name: mysql-router
        image: mysql/mysql-router:8.0.15
        env:
        - name: MYSQL_HOST
          value: mysql-0.mysql
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
        ports:
        - name: mysql-rw
          containerPort: 6446
        - name: mysql-ro
          containerPort: 6447
        - name: mysqlx-rw
          containerPort: 64460
        - name: mysqlx-ro
          containerPort: 64470
