---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: wordpress
data:
  nginx.conf: |
    user nginx;
    pid /run/nginx.pid;
    worker_processes 1;
    worker_rlimit_nofile 65535;

    events {
      multi_accept on;
      worker_connections 65535;
    }

    http {
      upstream php {
        server unix:/var/run/php/php7.3-fpm.sock;
      }

      charset utf-8;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      server_tokens off;
      log_not_found off;
      types_hash_max_size 2048;
      client_max_body_size 16M;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log warn;

      server {
        listen 80;

        server_name example.com;

        set $base /var/www/html;
        root $base/;

        index index.php;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline'" always;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;

        location / {
          try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
          try_files $fastcgi_script_name =404;

          include /etc/nginx/fastcgi_params;

          fastcgi_pass        php;
          fastcgi_index       index.php;
          fastcgi_buffers     8 16k;
          fastcgi_buffer_size 32k;

          fastcgi_param DOCUMENT_ROOT   $realpath_root;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/usr/lib/php/:/tmp/";
        }

        location = /wp-includes/js/tinymce/wp-tinymce.php {
          try_files $fastcgi_script_name =404;

          include /etc/nginx/fastcgi_params;

          fastcgi_pass        php;
          fastcgi_index       index.php;
          fastcgi_buffers     8 16k;
          fastcgi_buffer_size 32k;

          fastcgi_param DOCUMENT_ROOT   $realpath_root;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/usr/lib/php/:/tmp/";
        }

        location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
          expires 7d;
          access_log off;
        }

        location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
          add_header Access-Control-Allow-Origin "*";
          expires 7d;
          access_log off;
        }

        location ~ /\.(?!well-known) {
          deny all;
        }

        location ~* ^/(?:wp-content|wp-includes)/.*\.php$ {
          deny all;
        }

        location ~* ^/wp-content/uploads/.*\.(?:s?html?|php|js|swf)$ {
          deny all;
        }

        location ~ ^/wp-content/plugins {
          deny all;
        }

        location ~* \/wp-admin\/load-(?:scripts|styles)\.php {
          deny all;
        }

        location ~* ^/(?:xmlrpc\.php|wp-links-opml\.php|wp-config\.php|wp-config-sample\.php|wp-comments-post\.php|readme\.html|license\.txt)$ {
          deny all;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  php.ini: |
    [PHP]
    engine = On
    short_open_tag = Off
    precision = 14
    output_buffering = 4096
    zlib.output_compression = Off
    implicit_flush = Off
    serialize_precision = -1
    zend.enable_gc = On
    expose_php = On
    max_execution_time = 30
    max_input_time = 60
    memory_limit = 128M
    report_memleaks = On
    variables_order = "GPCS"
    request_order = "GP"
    register_argc_argv = Off
    auto_globals_jit = On
    post_max_size = 16M
    default_mimetype = "text/html"
    default_charset = "UTF-8"
    enable_dl = Off
    file_uploads = On
    upload_max_filesize = 16M
    max_file_uploads = 20
    allow_url_fopen = On
    allow_url_include = Off
    default_socket_timeout = 60

    [CLI Server]
    cli_server.color = On

    [sqlite3]
    sqlite3.defensive = 1

    [mail function]
    SMTP = localhost
    smtp_port = 25
    mail.add_x_header = Off

    [ODBC]
    odbc.allow_persistent = On
    odbc.check_persistent = On
    odbc.max_persistent = -1
    odbc.max_links = -1
    odbc.defaultlrl = 4096
    odbc.defaultbinmode = 1

    [Interbase]
    ibase.allow_persistent = 1
    ibase.max_persistent = -1
    ibase.max_links = -1
    ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
    ibase.dateformat = "%Y-%m-%d"
    ibase.timeformat = "%H:%M:%S"

    [MySQLi]
    mysqli.max_persistent = -1
    mysqli.allow_persistent = On
    mysqli.max_links = -1
    mysqli.default_port = 3306
    mysqli.reconnect = Off

    [mysqlnd]
    mysqlnd.collect_statistics = On
    mysqlnd.collect_memory_statistics = Off

    [PostgreSQL]
    pgsql.allow_persistent = On
    pgsql.auto_reset_persistent = Off
    pgsql.max_persistent = -1
    pgsql.max_links = -1
    pgsql.ignore_notice = 0
    pgsql.log_notice = 0

    [bcmath]
    bcmath.scale = 0

    [Session]
    session.save_handler = files
    session.use_strict_mode = 0
    session.use_cookies = 1
    session.use_only_cookies = 1
    session.name = PHPSESSID
    session.auto_start = 0
    session.cookie_lifetime = 0
    session.cookie_path = /
    session.serialize_handler = php
    session.gc_probability = 1
    session.gc_divisor = 1000
    session.gc_maxlifetime = 1440
    session.cache_limiter = nocache
    session.cache_expire = 180
    session.use_trans_sid = 0
    session.sid_length = 26
    session.trans_sid_tags = "a=href,area=href,frame=src,form="
    session.sid_bits_per_character = 5

    [Assertion]
    zend.assertions = -1

    [Tidy]
    tidy.clean_output = Off

    [soap]
    soap.wsdl_cache_enabled = 1
    soap.wsdl_cache_dir = "/tmp"
    soap.wsdl_cache_ttl = 86400
    soap.wsdl_cache_limit = 5

    [ldap]
    ldap.max_links = -1
  wp-config.php: |
    <?php
    define('DB_NAME',     'wordpress');
    define('DB_USER',     'wordpress');
    define('DB_PASSWORD', 'wordpress');
    define('DB_HOST',     '127.0.0.1:/var/run/mysqld/mysqld.sock');
    define('DB_CHARSET',  'utf8mb4');
    define('DB_COLLATE',  'utf8mb4_0900_ai_ci');

    define('AUTH_KEY',         '-w>7z?Z3mV`s9:ErgP)u|xbNH)K[BTV8`xA6s<K5*dPN>e(a*yPZt-Ui/uYo~Y}B');
    define('SECURE_AUTH_KEY',  '7O>gK0Lp?S_^4O&^V7gMNm(sxx7TwH*Vn.`;zQ*GHrnIJl+OcJ5dFg,2-[jDodk|');
    define('LOGGED_IN_KEY',    'U|lVSq+ ?Iw~i^5t)-aEuu h%3]|yc>xwZN8w~lP_n VU_}@PoMU-i998xLZIbLs');
    define('NONCE_KEY',        'oF3z!%>t)ffiQ^!b=Z*K?jt.y~iv@_yO:3r9{wd^Lx?|h/TgD+^C/o,B<Bv*<GlW');
    define('AUTH_SALT',        'RgN-l/@]`Z|8oQBT|w-{+kb7+tx}}-%RB--V=_-U5eexV34E:c?2NX}a7wBE+R*u');
    define('SECURE_AUTH_SALT', 'FsO3H@)3X#3a`&B Tu~-R3|i$ev-iU:iV~GdfjVfq&3-uD]K-s]|0 -On#q<*A6C');
    define('LOGGED_IN_SALT',   'B]v>d6>YN%N|$[v1fjW##HiE|B| EuTjgFL7o{ky31R@h(fI|N,_L-HF g,-n=DK');
    define('NONCE_SALT',       'eC=N `TpD4+XN+.F8H4A?G4m-*K Q3O!1h+C8DfquKO1QD`mDUdF@9hX-|;*w}M:');

    define('WP_DEBUG', false );

    $table_prefix = 'wp_';

    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
      $_SERVER['HTTPS'] = 'on';
    }

    if (!defined('ABSPATH')) {
      define('ABSPATH', dirname( __FILE__ ) . '/');
    }

    require_once(ABSPATH . 'wp-settings.php');
  zz-docker.conf: |
    [global]
    daemonize = no

    [www]
    listen = /var/run/php/php7.3-fpm.sock
    listen.owner = www-data
    listen.group = www-data
    listen.mode = 0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.15
        args:
        - --default-authentication-plugin=mysql_native_password
        - --performance_schema=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        volumeMounts:
        - name: wordpress-vol
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: wordpress-sock
          mountPath: /var/run/mysqld
          subPath: mysqld
      - name: wordpress
        image: wordpress:5.1.1-php7.3-fpm-alpine
        volumeMounts:
        - name: wordpress-vol
          mountPath: /var/www/html
          subPath: html
        - name: wordpress-config
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        - name: wordpress-config
          mountPath: /var/www/html/wp-config.php
          subPath: wp-config.php
        - name: wordpress-config
          mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
          subPath: zz-docker.conf
        - name: wordpress-sock
          mountPath: /var/run/php
          subPath: php
        - name: wordpress-sock
          mountPath: /var/run/mysqld
          subPath: mysqld
      - name: nginx
        image: nginx:1.15.10-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-vol
          mountPath: /var/www/html
          subPath: html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: wordpress-sock
          mountPath: /var/run/php
          subPath: php
      volumes:
      - name: wordpress-vol
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
            mode: 292
      - name: wordpress-config
        configMap:
          name: wordpress-config
          items:
          - key: php.ini
            path: php.ini
            mode: 292
          - key: wp-config.php
            path: wp-config.php
            mode: 292
          - key: zz-docker.conf
            path: zz-docker.conf
            mode: 292
      - name: wordpress-sock
        emptyDir:
          medium: Memory
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
